// generated 2002/9/24 17:04:33 CEST by christof@puck.petig-baender.de
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gtkmmversion 2.0 close_window.glade
// for gtk 2.0.6 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ././window1.cc

#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include "window1.hh"
#include <gtkmm/button.h>

window1_glade::window1_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *window1 = this;
   Gtk::Button *button1 = manage(new class Gtk::Button(_("spawn a new Window")));
   button1->set_flags(Gtk::CAN_FOCUS);
   window1->set_title(_("Parent Window"));
   window1->set_modal(false);
   window1->set_position(Gtk::WIN_POS_NONE);
   window1->add(*button1);
   button1->show();
   window1->show();
   button1->signal_clicked().connect(SigC::slot(*static_cast<class window1*>(this), &window1::on_button1_clicked));
   window1->signal_delete_event().connect(SigC::slot(*static_cast<class window1*>(this), &window1::on_window1_delete_event));
}

window1_glade::~window1_glade()
{  
}
