// generated 2002/9/24 17:04:34 CEST by christof@puck.petig-baender.de
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gtkmmversion 2.0 close_window.glade
// for gtk 2.0.6 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ././window2.hh and././window2.cc

#ifndef _WINDOW2_GLADE_HH
#  define _WINDOW2_GLADE_HH

#include <gtkmm/window.h>

class window2_glade : public Gtk::Window
{  
protected:
        
        
        window2_glade();
        
        ~window2_glade();
};
#endif
