// generated 2002/9/24 17:04:34 CEST by christof@puck.petig-baender.de
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gtkmmversion 2.0 close_window.glade
// for gtk 2.0.6 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ././window2.cc

#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include "window2.hh"
#include <gtkmm/button.h>

window2_glade::window2_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *window2 = this;
   Gtk::Button *button2 = manage(new class Gtk::Button(_("close me")));
   button2->set_flags(Gtk::CAN_FOCUS);
   window2->set_title(_("Child Window"));
   window2->set_modal(false);
   window2->set_position(Gtk::WIN_POS_NONE);
   window2->add(*button2);
   button2->show();
   window2->show();
   button2->signal_clicked().connect(SigC::slot(*static_cast<class window2*>(this), &window2::on_button2_clicked));
   window2->signal_delete_event().connect(SigC::slot(*static_cast<class window2*>(this), &window2::on_window2_delete_event));
}

window2_glade::~window2_glade()
{  
}
