// generated 2002/9/24 17:04:33 CEST by christof@puck.petig-baender.de
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gtkmmversion 2.0 close_window.glade
// for gtk 2.0.6 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ././window1.hh and././window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH

#include <gtkmm/window.h>

class window1_glade : public Gtk::Window
{  
protected:
        
        
        window1_glade();
        
        ~window1_glade();
};
#endif
