// generated 2003/4/9 8:41:54 CEST by christof@puck.petig-baender.de
// using glademm V1.1.3g_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- WinFileReq.glade
// for gtk 2.2.1 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/WinFileReq.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include "WinFileReq_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>

WinFileReq_glade::WinFileReq_glade(
) : Gtk::FileSelection("Datei auswhlen")
{  
   
   Gtk::FileSelection *WinFileReq = this;
   gmm_data = new GlademmData(get_accel_group());
   WinFileReq->get_ok_button()->set_flags(Gtk::CAN_FOCUS);
   WinFileReq->get_ok_button()->set_relief(Gtk::RELIEF_NORMAL);
   WinFileReq->get_cancel_button()->set_flags(Gtk::CAN_FOCUS);
   WinFileReq->get_cancel_button()->set_relief(Gtk::RELIEF_NORMAL);
   WinFileReq->set_border_width(10);
   WinFileReq->set_title("Datei auswhlen");
   WinFileReq->set_modal(false);
   WinFileReq->show();
   WinFileReq->get_ok_button()->signal_clicked().connect(SigC::slot(*this, &WinFileReq_glade::on_ok_button1_clicked));
   WinFileReq->get_cancel_button()->signal_clicked().connect(SigC::slot(*this, &WinFileReq_glade::on_cancel));
}

WinFileReq_glade::~WinFileReq_glade()
{  delete gmm_data;
}
