// generated 2008/6/28 12:14:36 CEST by christof@vesta.(none)
// using glademm V2.13.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- WinFileReq.glade
// for gtk 2.13.3 and gtkmm 2.12.7
//
// Please modify the corresponding derived classes in ./src/WinFileReq.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "WinFileReq_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

WinFileReq_glade::WinFileReq_glade(
) : Gtk::FileSelection("Datei auswhlen")
{  WinFileReq = this;
   gmm_data = new GlademmData(get_accel_group());
   WinFileReq->get_ok_button()->set_flags(Gtk::CAN_FOCUS);
   WinFileReq->get_ok_button()->set_flags(Gtk::CAN_DEFAULT);
   WinFileReq->get_cancel_button()->set_flags(Gtk::CAN_FOCUS);
   WinFileReq->get_cancel_button()->set_flags(Gtk::CAN_DEFAULT);
   WinFileReq->set_border_width(10);
   WinFileReq->set_title("Datei auswhlen");
   WinFileReq->show();
   WinFileReq->get_ok_button()->signal_clicked().connect(sigc::mem_fun(*this, &WinFileReq_glade::on_ok_button1_clicked), false);
   WinFileReq->get_cancel_button()->signal_clicked().connect(sigc::mem_fun(*this, &WinFileReq_glade::on_cancel), false);
}

WinFileReq_glade::~WinFileReq_glade()
{  delete gmm_data;
}
